version: "3.9"

services:
  patient-api:
    build: .
    container_name: patient-api-container

    ports:
      - "8000:8000"

    volumes:
      - patient-data:/app

    env_file:
      - .env

    restart: unless-stopped

volumes:
  patient-data: